### ISSUE TITLE
How to install required packages

### ISSUE THREAD

**Issue by jprine** [EnviroCentre/monitoring-module#1]
I'd like to use the monitoring-module packages to automate the loading of a bunch of data into Dss files.  I was able to install `EnviroCentre/jython-upgrade` and then install `monitoring-module` via the `deploy.ps1` script. I'm having trouble running the scripts because I don't know how to install the required packages `pyyam`l and `voluptuous`.

I've got a bunch of experience with "normal" Python, so I'd usually just do a `pip <package>` or whatever, but I don't know how the HEC-DSSVue / Jython environment is setup. Can I just copy the raw Python from the requirements in the site-packages in the Jython directory, or into the script directory? Is there a way to get a command-line from HEC-DSSVue or an interactive environment? I'm just new to this particular configuration.

Also, is the Jython update required for this to work? I installed it without a problem. It seems to work, except for some issues with the Script Editor (EnviroCentre/jython-upgrade#1). I usually edit in other software, so it's not a big deal, but the editor is nice for small fixes sometimes,

**Comment by faph** [comment]
As this package is somewhat experimental, I didn't want to publish the compiled installer (`/installer/win/installer.nsi`). If you know NSIS you can build the installer and this installer will both install the package (in the scripts user folder) and the requirements (in `jython\lib\site-packages\`).

I use the `deploy.ps1` during development.

You should actually be able to pip install the requirements as well into the `jython\lib\site-packages\` folder. Or just copy the files from the repo `src/lib` folder into site-packages.

Yes, the jython upgrade is required. I was fed up with the restrictions of jython 2.2!

**Comment by jprine** [comment]
> You should actually be able to pip install the requirements as well into the `jython/lib/site-packages/` folder. Or just copy the files from the repo `src/lib` folder into site-packages.

I see that pip has a `--target` flag.  Good to know.  I ended up just copying from `src/lib`into `site-packages` and it seems to work. Thanks.

> Yes, the jython upgrade is required. I was fed up with the restrictions of jython 2.2!

I know that... I was surprised when I tried to use the "modern" `.format` string method and got an error...
